//! Neural network weights for embedded AI policy.
//!
//! This module contains auto-generated weights for the MLP policy.
//! Weights are generated by `tools/gen_dummy_weights.py`.

mod generated;
pub mod loader;

pub use generated::{MODEL_SCHEMA_HASH, MODEL_SCHEMA_VERSION, layer1, layer2, layer3};
