[package]
name = "hearts-core"
version = "1.0.1"
edition = "2024"

[dependencies]
rand = { version = "0.8", features = ["std", "small_rng"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


